### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by carlosriveroib** [uloco/bluloco-dark-syntax#1]
Hello,

First of all, congratulations for this awesome theme. It's my favourite.
But at the moment it is deprecated. Could you update it? It would be really nice.

Thank you so much.

**Comment by uloco** [comment]
Hi, thanks for your props. Unfortunately I switched to using visual studio code, so I am not actively using this theme. This means, I cannot constantly update the code, because I am not aware of any bugs :) I will try to update the both themes dark and light, so that they stop being deprecated and hopefully find a solution to maintain those themes with a single code base (vscode, atom, webstorm).

**Comment by uloco** [comment]
I couldn't find a hint, why this theme is deprecated. How do you see this? I recently installed it and no hints about deprecation...

**Comment by carlosriveroib** [comment]
![sin titulo](https://user-images.githubusercontent.com/9528363/27807084-ebf5c634-603e-11e7-8a63-39b46634d9b3.png)
![sin titulo1](https://user-images.githubusercontent.com/9528363/27807089-ef9eeacc-603e-11e7-9e98-c266cd0d5586.png)

**Comment by uloco** [comment]
fixed with a97a0af7f640027e0bd3e1c65b51d0361e85b223

**Comment by carlosriveroib** [comment]
Thank you very much.
